services:
  ailab_web_app_dev:
    image: ailab/base
    container_name: ailab_web_app_dev
    entrypoint: ["npm", "run"]
    command: ["start", "--workspace=apps/web"]
    networks:
      ailab_network:
        aliases:
          - ailab_web_app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../:/home/ailab/app
      - /home/ailab/app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3031"]
      interval: 30s
      timeout: 10s
      retries: 5

  ailab_api_app_dev:
    image: ailab/base
    container_name: ailab_api_app_dev
    entrypoint: ["npm", "run"]
    command: ["start", "--workspace=apps/api"]
    networks:
      ailab_network:
        aliases:
          - ailab_api_app
    depends_on:
      - ailab_postgres
      - ailab_redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../:/home/ailab/app
      - /home/ailab/app/node_modules
      - ./hosts:/etc/hosts
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3030/api/system/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5

  ailab_nginx:
    depends_on:
      ailab_api_app_dev:
        condition: service_healthy
      ailab_web_app_dev:
        condition: service_healthy
    profiles:
      - development
